defaults:
  - HPT_config_schema
  - _self_

# LGBM HPT config 
HPT_model_name: "LGBM"
HPT_encoding: "Mixed"

hyperparameters:
  reg_alpha:
    type: float
    name: reg_alpha
    low: 0.1
    high: 10.0
  reg_lambda:
    type: float
    name: reg_lambda
    low: 0.1
    high: 10.0
  num_leaves:
    type: int
    name: num_leaves
    low: 2
    high: 512
  low_child_samples:
    type: int
    name: min_child_samples
    low: 5
    high: 100
  high_depth:
    type: int
    name: max_depth
    low: 3
    high: 12
  learning_rate:
    type: float
    name: learning_rate
    low: 0.001
    high: 1
  colsample_bytree:
    type: float
    name: colsample_bytree
    low: 0.1
    high: 1
  n_estimators:
    type: int
    name: n_estimators
    low: 100
    high: 1000
  n_jobs: 
    type: int
    name: n_jobs
    low: -1
    high: -1
  boosting_type:
    type: categorical
    name: boosting_type
    choices: [gbdt, dart]
  objective: 
    type: categorical
    name: objective
    choices: [binary]
  verbose:
    type: int
    name: verbose
    low: -1
    high: -1
  deterministic: 
    type: categorical
    name: deterministic
    choices: [True]


