defaults:
  - HPT_config_schema
  - _self_


HPT_model_name: "XGBoost"
HPT_encoding: "ME"
cat_feat_fit: False


hyperparameters:
  device:
    type: categorical
    name: device
    choices: ['gpu']
  verbosity:
    type: int
    name: verbosity
    low: 0
    high: 0
  n_estimators:
    type: int
    name: n_estimators
    low: 200
    high: 1000
  max_depth:
    type: int
    name: max_depth
    low: 3
    high: 12
  min_child_weight:
    type: int
    name: min_child_weight
    low: 1
    high: 10
  learning_rate:
    type: float
    name: learning_rate
    low: 0.001
    high: 0.1
  subsample:
    type: float
    name: subsample
    low: 0.3
    high: 1.0 
  colsample_bytree:
    type: float
    name: colsample_bytree
    low: 0.3
    high: 1.0 
  tree_method:
    type: categorical
    name: tree_method
    choices: ['gpu_hist']   
  objective:
    type: categorical
    name: objective
    choices: ['binary:logistic']
  eval_metric:
    type: categorical
    name: eval_metric
    choices: ['logloss', 'mae', 'auc']
  booster:
    type: categorical
    name: booster
    choices: ['gbtree']
  gamma:  
    type: float
    name: gamma
    low: 0.01
    high: 10
    log: True
  alpha:
    type: float
    name: alpha
    low: 0.01
    high: 10
    log: True
  lambda:
    type: float
    name: lambda
    low: 0.01
    high: 10
    log: True
  